const API='https://football-signal-ai-basic-ke0gnub7u.vercel.app';
const $=id=>document.getElementById(id);
const state={date:null,games:[],selected:null,timer:null,busy:false};
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtTime(f){const d=new Date(f.start||f.timestamp);return isNaN(d)?'--:--':d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function renderDays(){const now=new Date();let html='';for(let i=0;i<8;i++){const d=new Date(now);d.setDate(d.getDate()+i);const key=dateKey(d),label=i===0?'Hoje':i===1?'Amanhã':d.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'2-digit'});html+=`<button class="day ${state.date===key?'active':''}" data-date="${key}">${label}</button>`}$('days').innerHTML=html;document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;renderDays();loadGames()})}
function renderLeagues(){const current=$('league').value;const leagues=[...new Set(state.games.map(g=>g.league).filter(Boolean))].sort();$('league').innerHTML='<option value="">Todos os campeonatos</option>'+leagues.map(x=>`<option>${esc(x)}</option>`).join('');if(leagues.includes(current))$('league').value=current}
function filtered(){const q=$('search').value.trim().toLowerCase(),lg=$('league').value;return state.games.filter(g=>(!lg||g.league===lg)&&(!q||`${g.home.name} ${g.away.name} ${g.league}`.toLowerCase().includes(q)))}
function renderGames(){const rows=filtered();$('count').textContent=`${rows.length} jogos • ${state.date===dateKey(new Date())?'Hoje':state.date}`;if(!rows.length){$('games').innerHTML='<div class="empty">Nenhum jogo encontrado.</div>';return}const groups=new Map();for(const g of rows){const k=g.league||'Outros campeonatos';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(g)}let html='';for(const [league,list] of groups){html+=`<div class="league"><div class="league-title"><b>${esc(league)}</b><span>${list.length} jogos</span></div>`;for(const g of list){const score=(g.score?.home!==null&&g.score?.away!==null)?`<span class="score">${g.score.home}–${g.score.away}</span>`:'';html+=`<div class="match"><div class="match-top"><div class="time">${fmtTime(g)}</div><div class="teams"><div class="team">${esc(g.home.name)}</div><div class="team">${esc(g.away.name)}</div></div><div class="state ${g.live?'live':''}">${score||esc(g.live?'AO VIVO':g.state||'Agendado')}</div></div></div>`}html+='</div>'}$('games').innerHTML=html}
async function loadGames(){if(state.busy)return;state.busy=true;$('robotText').textContent='ATUALIZANDO…';$('games').innerHTML='<div class="empty">Carregando jogos…</div>';try{const url=`${API}/api/fixtures?date=${encodeURIComponent(state.date)}`;const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);state.games=Array.isArray(d.games)?d.games:[];renderLeagues();renderGames();$('updated').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('sources').innerHTML=`<span class="pill">Sportmonks ${d.sources?.sportmonks||0}</span><span class="pill">football-data ${d.sources?.footballData||0}</span><span class="pill">ESPN ${d.sources?.espn||0}</span>`}catch(err){$('games').innerHTML=`<div class="error">Falha: ${esc(err.message)}</div>`;$('count').textContent='Falha ao carregar'}finally{state.busy=false;$('robotText').textContent='ROBÔ ATIVO'}}
function init(){state.date=dateKey(new Date());renderDays();$('search').oninput=renderGames;$('league').onchange=renderGames;if($('save'))$('save').onclick=loadGames;if($('clear'))$('clear').onclick=loadGames;if($('toggleConfig'))$('toggleConfig').onclick=()=>{$('configBody').classList.toggle('hidden')};loadGames();state.timer=setInterval(loadGames,60000)}
init();