const SM = 'https://api.sportmonks.com/v3/football';
const FD = 'https://api.football-data.org/v4';
function token(req, envName, headerName){return process.env[envName]||req.headers[headerName]||''}
function tokens(req){return {sm:token(req,'SPORTMONKS_TOKEN','x-sportmonks-token'),fd:token(req,'FOOTBALL_DATA_TOKEN','x-football-data-token'),odds:token(req,'ODDS_API_KEY','x-odds-api-key')}}
function send(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-methods','GET, OPTIONS');res.setHeader('access-control-allow-headers','Content-Type, X-Sportmonks-Token, X-Football-Data-Token, X-Odds-Api-Key');res.end(JSON.stringify(body))}
async function fetchJson(url,options={},timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...options,signal:ctl.signal});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok){const e=new Error(data?.message||data?.error||`HTTP ${r.status}`);e.status=r.status;e.body=data;throw e}return {data,headers:r.headers}}finally{clearTimeout(timer)}}
function smUrl(path,tokenValue,params={}){const u=new URL(SM+path);u.searchParams.set('api_token',tokenValue);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});return u.toString()}
function cleanName(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|sc|ac|club|clube|deportivo|futebol)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function isoDate(d){const x=new Date(d);return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(x.getUTCDate()).padStart(2,'0')}`}
function smParticipants(f){const ps=Array.isArray(f?.participants)?f.participants:[];return {home:ps.find(x=>x?.meta?.location==='home')||ps[0]||{},away:ps.find(x=>x?.meta?.location==='away')||ps[1]||{}}}
function smScore(f){const scores=Array.isArray(f?.scores)?f.scores:[];let h=null,a=null;for(const s of scores){const goals=Number(s?.score?.goals),side=s?.score?.participant;if(Number.isFinite(goals)&&side==='home')h=goals;if(Number.isFinite(goals)&&side==='away')a=goals}return {home:h,away:a}}
function normalizeSM(f){const {home,away}=smParticipants(f),sc=smScore(f);return {id:String(f.id),provider:'sportmonks',providerId:String(f.id),start:f.starting_at?String(f.starting_at).replace(' ','T')+'Z':null,timestamp:f.starting_at_timestamp?Number(f.starting_at_timestamp)*1000:null,league:f.league?.name||f.league?.data?.name||`Liga ${f.league_id||''}`.trim(),country:f.league?.country?.name||f.country?.name||'',home:{id:home.id?String(home.id):'',name:home.name||'Casa',logo:home.image_path||''},away:{id:away.id?String(away.id):'',name:away.name||'Fora',logo:away.image_path||''},state:f.state?.short_name||f.state?.name||String(f.state_id||''),live:[2,3,4,6,7,9,22].includes(Number(f.state_id)),finished:[5,8,11,12,13,14,15,16,17].includes(Number(f.state_id)),score:sc,hasOdds:!!(f.has_odds||f.has_premium_odds)}}
function normalizeFD(m){return {id:'fd-'+String(m.id),provider:'football-data',providerId:String(m.id),start:m.utcDate||null,timestamp:m.utcDate?Date.parse(m.utcDate):null,league:m.competition?.name||'',country:m.area?.name||m.competition?.area?.name||'',home:{id:m.homeTeam?.id?String(m.homeTeam.id):'',name:m.homeTeam?.name||'Casa',logo:m.homeTeam?.crest||''},away:{id:m.awayTeam?.id?String(m.awayTeam.id):'',name:m.awayTeam?.name||'Fora',logo:m.awayTeam?.crest||''},state:m.status||'',live:['IN_PLAY','PAUSED'].includes(m.status),finished:m.status==='FINISHED',score:{home:m.score?.fullTime?.home??null,away:m.score?.fullTime?.away??null},hasOdds:false}}
function matchKey(f){const t=f.timestamp?Math.round(f.timestamp/3600000):0;return `${cleanName(f.home?.name)}|${cleanName(f.away?.name)}|${t}`}
function mergeGames(primary=[],secondary=[]){const map=new Map();for(const f of [...primary,...secondary]){const k=matchKey(f),old=map.get(k);if(!old||(old.provider!=='sportmonks'&&f.provider==='sportmonks'))map.set(k,f)}return [...map.values()].sort((a,b)=>(a.timestamp||0)-(b.timestamp||0))}
function resultFromFixture(f,teamId){const {home}=smParticipants(f),sc=smScore(f);if(sc.home===null||sc.away===null)return null;const isHome=String(home.id)===String(teamId),gf=isHome?sc.home:sc.away,ga=isHome?sc.away:sc.home;return gf>ga?'W':gf<ga?'L':'D'}
function formStats(fixtures,teamId,max=10){const done=(fixtures||[]).filter(x=>{const s=smScore(x);return s.home!==null&&s.away!==null}).sort((a,b)=>(b.starting_at_timestamp||0)-(a.starting_at_timestamp||0)).slice(0,max);let pts=0,w=0,d=0,l=0;for(const f of done){const r=resultFromFixture(f,teamId);if(r==='W'){pts+=3;w++}else if(r==='D'){pts++;d++}else if(r==='L')l++}return {n:done.length,w,d,l,ppg:done.length?pts/done.length:0}}
function h2hStats(fixtures,homeId,awayId,max=10){const done=(fixtures||[]).filter(x=>{const s=smScore(x);return s.home!==null&&s.away!==null}).slice(0,max);let home=0,draw=0,away=0;for(const f of done){const p=smParticipants(f),sc=smScore(f);if(sc.home===sc.away){draw++;continue}const winnerId=sc.home>sc.away?String(p.home.id):String(p.away.id);if(winnerId===String(homeId))home++;else if(winnerId===String(awayId))away++}return {n:done.length,home,draw,away}}
function oddsTriplet(){return null}
function probabilityEngine(){return {probabilities:{home:42,draw:29,away:29},favorite:'home',confidence:'Baixa',quality:20,sources:['Base']}}
module.exports={tokens,send,fetchJson,smUrl,FD,normalizeSM,normalizeFD,mergeGames,smParticipants,smScore,formStats,h2hStats,oddsTriplet,probabilityEngine,isoDate};