const SM = 'https://api.sportmonks.com/v3/football';
const FD = 'https://api.football-data.org/v4';
function token(req, envName, headerName){return process.env[envName]||req.headers[headerName]||''}
function tokens(req){return {sm:token(req,'SPORTMONKS_TOKEN','x-sportmonks-token'),fd:token(req,'FOOTBALL_DATA_TOKEN','x-football-data-token'),odds:token(req,'ODDS_API_KEY','x-odds-api-key')}}
function send(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-methods','GET, OPTIONS');res.setHeader('access-control-allow-headers','Content-Type, X-Sportmonks-Token, X-Football-Data-Token, X-Odds-Api-Key');res.end(JSON.stringify(body))}
async function fetchJson(url,options={},timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...options,signal:ctl.signal});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={message:text}}if(!r.ok){const e=new Error(data?.message||data?.error||`HTTP ${r.status}`);e.status=r.status;e.body=data;throw e}return {data,headers:r.headers}}finally{clearTimeout(timer)}}
function smUrl(path,tokenValue,params={}){const u=new URL(SM+path);u.searchParams.set('api_token',tokenValue);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});return u.toString()}
function cleanName(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|sc|ac|club|clube|deportivo|futebol)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function isoDate(d){const x=new Date(d);return `${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,'0')}-${String(x.getUTCDate()).padStart(2,'0')}`}
function smParticipants(f){const ps=Array.isArray(f?.participants)?f.participants:[];return {home:ps.find(x=>x?.meta?.location==='home')||ps[0]||{},away:ps.find(x=>x?.meta?.location==='away')||ps[1]||{}}}
function smScore(f){const scores=Array.isArray(f?.scores)?f.scores:[];let h=null,a=null;for(const s of scores){const goals=Number(s?.score?.goals),side=s?.score?.participant;if(Number.isFinite(goals)&&side==='home')h=goals;if(Number.isFinite(goals)&&side==='away')a=goals}return {home:h,away:a}}
function normalizeSM(f){const {home,away}=smParticipants(f),sc=smScore(f);return {id:String(f.id),provider:'sportmonks',providerId:String(f.id),start:f.starting_at?String(f.starting_at).replace(' ','T')+'Z':null,timestamp:f.starting_at_timestamp?Number(f.starting_at_timestamp)*1000:null,league:f.league?.name||f.league?.data?.name||`Liga ${f.league_id||''}`.trim(),country:f.league?.country?.name||f.country?.name||'',home:{id:home.id?String(home.id):'',name:home.name||'Casa',logo:home.image_path||''},away:{id:away.id?String(away.id):'',name:away.name||'Fora',logo:away.image_path||''},state:f.state?.short_name||f.state?.name||String(f.state_id||''),live:[2,3,4,6,7,9,22].includes(Number(f.state_id)),finished:[5,8,11,12,13,14,15,16,17].includes(Number(f.state_id)),score:sc,hasOdds:!!(f.has_odds||f.has_premium_odds)}}
function normalizeFD(m){return {id:'fd-'+String(m.id),provider:'football-data',providerId:String(m.id),start:m.utcDate||null,timestamp:m.utcDate?Date.parse(m.utcDate):null,league:m.competition?.name||'',country:m.area?.name||m.competition?.area?.name||'',home:{id:m.homeTeam?.id?String(m.homeTeam.id):'',name:m.homeTeam?.name||'Casa',logo:m.homeTeam?.crest||''},away:{id:m.awayTeam?.id?String(m.awayTeam.id):'',name:m.awayTeam?.name||'Fora',logo:m.awayTeam?.crest||''},state:m.status||'',live:['IN_PLAY','PAUSED'].includes(m.status),finished:m.status==='FINISHED',score:{home:m.score?.fullTime?.home??null,away:m.score?.fullTime?.away??null},hasOdds:false}}
function matchKey(f){const t=f.timestamp?Math.round(f.timestamp/3600000):0;return `${cleanName(f.home?.name)}|${cleanName(f.away?.name)}|${t}`}
function mergeGames(primary=[],secondary=[]){const map=new Map();for(const f of [...primary,...secondary]){const k=matchKey(f),old=map.get(k);if(!old||(old.provider!=='sportmonks'&&f.provider==='sportmonks'))map.set(k,f)}return [...map.values()].sort((a,b)=>(a.timestamp||0)-(b.timestamp||0))}
function resultFromFixture(f,teamId){const {home}=smParticipants(f),sc=smScore(f);if(sc.home===null||sc.away===null)return null;const isHome=String(home.id)===String(teamId),gf=isHome?sc.home:sc.away,ga=isHome?sc.away:sc.home;return gf>ga?'W':gf<ga?'L':'D'}
function formStats(fixtures,teamId,max=10){const done=(fixtures||[]).filter(x=>{const s=smScore(x);return s.home!==null&&s.away!==null}).sort((a,b)=>(b.starting_at_timestamp||0)-(a.starting_at_timestamp||0)).slice(0,max);let pts=0,w=0,d=0,l=0;for(const f of done){const r=resultFromFixture(f,teamId);if(r==='W'){pts+=3;w++}else if(r==='D'){pts++;d++}else if(r==='L')l++}return {n:done.length,w,d,l,ppg:done.length?pts/done.length:0}}
function h2hStats(fixtures,homeId,awayId,max=10){const done=(fixtures||[]).filter(x=>{const s=smScore(x);return s.home!==null&&s.away!==null}).slice(0,max);let home=0,draw=0,away=0;for(const f of done){const p=smParticipants(f),sc=smScore(f);if(sc.home===sc.away){draw++;continue}const winnerId=sc.home>sc.away?String(p.home.id):String(p.away.id);if(winnerId===String(homeId))home++;else if(winnerId===String(awayId))away++}return {n:done.length,home,draw,away}}
function oddsTriplet(rows=[],homeName='',awayName=''){const vals={home:[],draw:[],away:[]};for(const r of rows||[]){const label=cleanName(r?.label||r?.name||r?.market_description||r?.value_name||''),v=Number(r?.value??r?.odd??r?.decimal);if(!Number.isFinite(v)||v<=1)continue;if(label==='1'||label.includes('home')||label===cleanName(homeName))vals.home.push(v);else if(label==='x'||label.includes('draw')||label.includes('empate'))vals.draw.push(v);else if(label==='2'||label.includes('away')||label===cleanName(awayName))vals.away.push(v)}if(!vals.home.length||!vals.draw.length||!vals.away.length)return null;return ['home','draw','away'].map(k=>vals[k].reduce((a,b)=>a+b,0)/vals[k].length)}
function norm3(a,b,c){a=Math.max(.001,a);b=Math.max(.001,b);c=Math.max(.001,c);const s=a+b+c;let h=Math.round(a/s*100),d=Math.round(b/s*100),aw=100-h-d;return {home:h,draw:d,away:aw}}
function probabilityEngine({odds,homeForm,awayForm,h2h}={}){let components=[],sources=[];if(Array.isArray(odds)&&odds.length===3&&odds.every(x=>Number(x)>1)){components.push({w:.6,p:norm3(1/odds[0],1/odds[1],1/odds[2])});sources.push('Odds de mercado')}const hn=homeForm?.n||0,an=awayForm?.n||0;if(hn&&an){const hp=(homeForm.ppg||0)/3,ap=(awayForm.ppg||0)/3,dp=Math.max(.12,1-Math.abs(hp-ap))*.32;components.push({w:.28,p:norm3(hp+.12,dp,ap)});sources.push('Forma recente')}if(h2h?.n){components.push({w:.12,p:norm3(h2h.home+1,h2h.draw+1,h2h.away+1)});sources.push('Confrontos diretos')}if(!components.length)return {probabilities:null,favorite:null,confidence:'Indisponível',quality:0,sources:[]};const tw=components.reduce((s,x)=>s+x.w,0),raw=components.reduce((o,x)=>({home:o.home+x.p.home*x.w,draw:o.draw+x.p.draw*x.w,away:o.away+x.p.away*x.w}),{home:0,draw:0,away:0}),p=norm3(raw.home/tw,raw.draw/tw,raw.away/tw),favorite=Object.entries(p).sort((a,b)=>b[1]-a[1])[0][0],mx=p[favorite],quality=Math.min(100,Math.round((odds?55:0)+Math.min(25,(hn+an)*1.25)+Math.min(20,(h2h?.n||0)*2))),confidence=mx>=60&&quality>=65?'Alta':mx>=48&&quality>=40?'Média':'Baixa';return {probabilities:p,favorite,confidence,quality,sources}}
module.exports={tokens,send,fetchJson,smUrl,FD,normalizeSM,normalizeFD,mergeGames,smParticipants,smScore,formStats,h2hStats,oddsTriplet,probabilityEngine,isoDate};