const {tokens,send,fetchJson,smUrl,FD,normalizeSM,normalizeFD,mergeGames}=require('./_lib');
const DEFAULT_FD='0cee141300874d2296cbfdfb5ec6eb7b';
// Cobertura ampliada tomando como referência as competições exibidas publicamente na Betnacional.
// A Betnacional é usada apenas como referência de cobertura; os dados continuam vindo das APIs integradas.
const ESPN_LEAGUES=['all','bra.1','bra.2','bra.3','bra.copa_do_brazil','conmebol.libertadores','conmebol.sudamericana','eng.1','eng.2','esp.1','ger.1','ita.1','fra.1','por.1','ned.1','ned.2','bel.1','aut.1','den.1','den.2','bul.1','fin.1','fin.2','col.1','uru.1','chi.1','arg.1','usa.1','usa.nwsl','mex.1','uefa.champions','uefa.europa','uefa.europa.conf','fifa.friendly','club.friendly'];
function normalizeESPN(e,leagueHint=''){const c=(e.competitions||[])[0]||{},teams=c.competitors||[],home=teams.find(x=>x.homeAway==='home')||teams[0]||{},away=teams.find(x=>x.homeAway==='away')||teams[1]||{},st=c.status?.type||e.status?.type||{},state=st.description||st.detail||st.name||'',completed=Boolean(st.completed),live=Boolean(!completed&&(st.state==='in'||/in progress|halftime|half|1st|2nd|extra time|penalt|live/i.test(state))),hs=Number(home.score),as=Number(away.score);return{id:'espn-'+String(e.id),provider:'espn',providerId:String(e.id),start:e.date||null,timestamp:e.date?Date.parse(e.date):null,league:e.league?.name||c.type?.text||e.season?.slug||leagueHint||'Futebol',country:'',home:{id:home.team?.id?String(home.team.id):'',name:home.team?.displayName||home.team?.name||'Casa',logo:home.team?.logo||''},away:{id:away.team?.id?String(away.team.id):'',name:away.team?.displayName||away.team?.name||'Fora',logo:away.team?.logo||''},state:state||'Agendado',live,finished:completed,score:{home:Number.isFinite(hs)?hs:null,away:Number.isFinite(as)?as:null},hasOdds:false}}
async function espnLeague(league,ymd){const url=`https://site.api.espn.com/apis/site/v2/sports/soccer/${league}/scoreboard?dates=${ymd}&limit=1000`;const {data}=await fetchJson(url,{headers:{Accept:'application/json','User-Agent':'Mozilla/5.0'}},8000);return (data?.events||[]).map(e=>normalizeESPN(e,league))}
function normalizeSofa(e){const s=e.status||{},hs=Number(e.homeScore?.current),as=Number(e.awayScore?.current),ts=Number(e.startTimestamp)||0;return{id:'sofa-'+e.id,provider:'sofascore',providerId:String(e.id),start:ts?new Date(ts*1000).toISOString():null,timestamp:ts?ts*1000:null,league:e.tournament?.name||e.uniqueTournament?.name||'Futebol',country:e.tournament?.category?.name||e.category?.name||'',home:{id:String(e.homeTeam?.id||''),name:e.homeTeam?.name||'Casa',logo:e.homeTeam?.id?`https://api.sofascore.app/api/v1/team/${e.homeTeam.id}/image`:''},away:{id:String(e.awayTeam?.id||''),name:e.awayTeam?.name||'Fora',logo:e.awayTeam?.id?`https://api.sofascore.app/api/v1/team/${e.awayTeam.id}/image`:''},state:s.description||s.type||'Ao vivo',live:!['finished','canceled','postponed'].includes(String(s.type||'').toLowerCase()),finished:String(s.type||'').toLowerCase()==='finished',score:{home:Number.isFinite(hs)?hs:null,away:Number.isFinite(as)?as:null},hasOdds:false}}
async function sofaLive(){const urls=['https://api.sofascore.com/api/v1/sport/football/events/live','https://www.sofascore.com/api/v1/sport/football/events/live'];let last;for(const url of urls){try{const {data}=await fetchJson(url,{headers:{Accept:'application/json','User-Agent':'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9,en;q=0.8','Referer':'https://www.sofascore.com/'}},12000);const games=(data?.events||[]).map(normalizeSofa).filter(g=>g.live);if(games.length)return games;last=new Error('feed retornou 0 jogos')}catch(e){last=e}}throw last||new Error('feed indisponível')}
module.exports=async function handler(req,res){if(req.method==='OPTIONS')return send(res,200,{ok:true});if(req.method!=='GET')return send(res,405,{error:'Use GET'});let {sm,fd}=tokens(req);fd=fd||DEFAULT_FD;const date=String(req.query?.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return send(res,400,{error:'date deve ser YYYY-MM-DD'});const errors=[],sources={sportmonks:0,footballData:0,espn:0,sofascoreLive:0};let a=[],b=[],c=[],d=[];
if(sm)try{let page=1,all=[],more=true;while(more&&page<=20){const {data}=await fetchJson(smUrl(`/fixtures/date/${date}`,sm,{include:'participants;league.country;state;scores',per_page:50,page}),{},12000),x=Array.isArray(data?.data)?data.data:[];all.push(...x);const p=data?.pagination||{};more=Boolean(p.has_more)||(p.current_page&&p.last_page&&p.current_page<p.last_page);if(!x.length)more=false;page++}a=all.map(normalizeSM);sources.sportmonks=a.length}catch(e){errors.push(`Sportmonks: ${e.message}`)}
try{const u=new URL(FD+'/matches');u.searchParams.set('dateFrom',date);u.searchParams.set('dateTo',date);const {data}=await fetchJson(u.toString(),{headers:{'X-Auth-Token':fd}},12000);b=(data?.matches||[]).map(normalizeFD);sources.footballData=b.length}catch(e){errors.push(`football-data: ${e.message}`)}
const ymd=date.replace(/-/g,'');const tasks=[...ESPN_LEAGUES.map(l=>espnLeague(l,ymd)),sofaLive()];const settled=await Promise.allSettled(tasks);for(let i=0;i<ESPN_LEAGUES.length;i++){const r=settled[i];if(r.status==='fulfilled')c.push(...r.value);else errors.push(`ESPN ${ESPN_LEAGUES[i]}: ${r.reason?.message||'erro'}`)}const sr=settled[ESPN_LEAGUES.length];if(sr?.status==='fulfilled')d=sr.value;else errors.push(`Sofascore live: ${sr?.reason?.message||'erro'}`);sources.espn=c.length;sources.sofascoreLive=d.length;
let games=mergeGames(mergeGames(mergeGames(a,b),c),d);games=games.sort((x,y)=>(Number(y.live)-Number(x.live))||((x.timestamp||0)-(y.timestamp||0)));return send(res,200,{date,count:games.length,liveCount:games.filter(g=>g.live).length,games,sources,reference:'Betnacional public football coverage',errors})};