const {tokens,send,fetchJson,smUrl,FD,normalizeSM,normalizeFD,mergeGames}=require('./_lib');
const DEFAULT_FD='0cee141300874d2296cbfdfb5ec6eb7b';
const ESPN_LEAGUES=['all','bra.1','bra.2','bra.3','bra.copa_do_brazil','conmebol.libertadores','conmebol.sudamericana','eng.1','eng.2','esp.1','ger.1','ita.1','fra.1','por.1','ned.1','ned.2','bel.1','aut.1','den.1','den.2','bul.1','fin.1','fin.2','col.1','uru.1','chi.1','arg.1','usa.1','usa.nwsl','mex.1','uefa.champions','uefa.europa','uefa.europa.conf','fifa.friendly','club.friendly'];
function norm3(a,b,c){a=Math.max(.001,a);b=Math.max(.001,b);c=Math.max(.001,c);const s=a+b+c;let h=Math.round(a/s*100),d=Math.round(b/s*100),aw=100-h-d;return {home:h,draw:d,away:aw}}
function americanToDecimal(x){x=Number(x);if(!Number.isFinite(x)||x===0)return null;return x>0?1+x/100:1+100/Math.abs(x)}
function oddsToProb(home,draw,away){const h=Number(home),d=Number(draw),a=Number(away);if(![h,d,a].every(x=>Number.isFinite(x)&&x>1))return null;return norm3(1/h,1/d,1/a)}
function espnOdds(c){const o=Array.isArray(c?.odds)?c.odds[0]:c?.odds;if(!o)return null;let hd=o.homeTeamOdds||o.homeOdds||{},ad=o.awayTeamOdds||o.awayOdds||{},dd=o.drawOdds||{};let h=Number(hd.decimalOdds||hd.decimal||hd.value),a=Number(ad.decimalOdds||ad.decimal||ad.value),d=Number(dd.decimalOdds||dd.decimal||dd.value);if(!(h>1))h=americanToDecimal(hd.moneyLine||hd.moneyline);if(!(a>1))a=americanToDecimal(ad.moneyLine||ad.moneyline);if(!(d>1))d=americanToDecimal(dd.moneyLine||dd.moneyline);return oddsToProb(h,d,a)}
function normalizeESPN(e,leagueHint=''){const c=(e.competitions||[])[0]||{},teams=c.competitors||[],home=teams.find(x=>x.homeAway==='home')||teams[0]||{},away=teams.find(x=>x.homeAway==='away')||teams[1]||{},st=c.status?.type||e.status?.type||{},state=st.description||st.detail||st.name||'',completed=Boolean(st.completed),live=Boolean(!completed&&(st.state==='in'||/in progress|halftime|half|1st|2nd|extra time|penalt|live/i.test(state))),hs=Number(home.score),as=Number(away.score),market=espnOdds(c),score={home:Number.isFinite(hs)?hs:null,away:Number.isFinite(as)?as:null};return{id:'espn-'+String(e.id),provider:'espn',providerId:String(e.id),competitionKey:leagueHint,start:e.date||null,timestamp:e.date?Date.parse(e.date):null,league:e.league?.name||c.type?.text||e.season?.slug||leagueHint||'Futebol',country:'',home:{id:home.team?.id?String(home.team.id):'',name:home.team?.displayName||home.team?.name||'Casa',logo:home.team?.logo||''},away:{id:away.team?.id?String(away.team.id):'',name:away.team?.displayName||away.team?.name||'Fora',logo:away.team?.logo||''},state:state||'Agendado',live,finished:completed,score,hasOdds:!!market,probabilities:market,probabilitySource:market?'odds de mercado ESPN':'',probabilityQuality:market?70:0}}
async function espnLeague(league,ymd){const url=`https://site.api.espn.com/apis/site/v2/sports/soccer/${league}/scoreboard?dates=${ymd}&limit=1000`;const {data}=await fetchJson(url,{headers:{Accept:'application/json','User-Agent':'Mozilla/5.0'}},8000);return (data?.events||[]).map(e=>normalizeESPN(e,league))}
function normalizeSofa(e){const s=e.status||{},type=String(s.type||'').toLowerCase(),hs=Number(e.homeScore?.current),as=Number(e.awayScore?.current),ts=Number(e.startTimestamp)||0,state=s.description||s.type||'Agendado',live=['inprogress','live','halftime','1sthalf','2ndhalf','extra_time','penalties'].includes(type)||/in progress|half|live|extra time|penalt/i.test(String(state)),finished=type==='finished',score={home:Number.isFinite(hs)?hs:null,away:Number.isFinite(as)?as:null};return{id:'sofa-'+e.id,provider:'sofascore',providerId:String(e.id),competitionKey:String(e.tournament?.uniqueTournament?.id||e.uniqueTournament?.id||e.tournament?.id||''),start:ts?new Date(ts*1000).toISOString():null,timestamp:ts?ts*1000:null,league:e.tournament?.uniqueTournament?.name||e.uniqueTournament?.name||e.tournament?.name||'Futebol',country:e.tournament?.category?.name||e.category?.name||'',home:{id:String(e.homeTeam?.id||''),name:e.homeTeam?.name||'Casa',logo:e.homeTeam?.id?`https://api.sofascore.app/api/v1/team/${e.homeTeam.id}/image`:''},away:{id:String(e.awayTeam?.id||''),name:e.awayTeam?.name||'Fora',logo:e.awayTeam?.id?`https://api.sofascore.app/api/v1/team/${e.awayTeam.id}/image`:''},state,live,finished,score,hasOdds:false,probabilities:null,probabilitySource:'',probabilityQuality:0}}
const sofaHeaders={Accept:'application/json','User-Agent':'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/126 Safari/537.36','Accept-Language':'pt-BR,pt;q=0.9,en;q=0.8','Referer':'https://www.sofascore.com/'};
async function sofaLive(){const urls=['https://api.sofascore.com/api/v1/sport/football/events/live','https://www.sofascore.com/api/v1/sport/football/events/live'];let last;for(const url of urls){try{const {data}=await fetchJson(url,{headers:sofaHeaders},12000);const games=(data?.events||[]).map(normalizeSofa).filter(g=>g.live);if(games.length)return games;last=new Error('feed retornou 0 jogos')}catch(e){last=e}}throw last||new Error('feed indisponível')}
async function sofaScheduled(date){const urls=[`https://www.sofascore.com/api/v1/sport/football/scheduled-events/${date}`,`https://api.sofascore.com/api/v1/sport/football/scheduled-events/${date}`];let last;for(const url of urls){try{const {data}=await fetchJson(url,{headers:sofaHeaders},14000);const games=(data?.events||[]).map(normalizeSofa);if(games.length)return games;last=new Error('agenda retornou 0 jogos')}catch(e){last=e}}throw last||new Error('agenda indisponível')}
module.exports=async function handler(req,res){if(req.method==='OPTIONS')return send(res,200,{ok:true});if(req.method!=='GET')return send(res,405,{error:'Use GET'});let {sm,fd}=tokens(req);fd=fd||DEFAULT_FD;const date=String(req.query?.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return send(res,400,{error:'date deve ser YYYY-MM-DD'});const errors=[],sources={sportmonks:0,footballData:0,espn:0,sofascoreSchedule:0,sofascoreLive:0};let a=[],b=[],c=[],d=[],e=[];
if(sm)try{let page=1,all=[],more=true;while(more&&page<=20){const {data}=await fetchJson(smUrl(`/fixtures/date/${date}`,sm,{include:'participants;league.country;state;scores',per_page:50,page}),{},12000),x=Array.isArray(data?.data)?data.data:[];all.push(...x);const p=data?.pagination||{};more=Boolean(p.has_more)||(p.current_page&&p.last_page&&p.current_page<p.last_page);if(!x.length)more=false;page++}a=all.map(normalizeSM).map(g=>({...g,competitionKey:String(g.league||''),probabilities:null,probabilitySource:'',probabilityQuality:0}));sources.sportmonks=a.length}catch(err){errors.push(`Sportmonks: ${err.message}`)}
try{const u=new URL(FD+'/matches');u.searchParams.set('dateFrom',date);u.searchParams.set('dateTo',date);const {data}=await fetchJson(u.toString(),{headers:{'X-Auth-Token':fd}},12000);b=(data?.matches||[]).map(normalizeFD).map(g=>({...g,competitionKey:String(g.league||''),probabilities:null,probabilitySource:'',probabilityQuality:0}));sources.footballData=b.length}catch(err){errors.push(`football-data: ${err.message}`)}
const ymd=date.replace(/-/g,'');const tasks=[...ESPN_LEAGUES.map(l=>espnLeague(l,ymd)),sofaScheduled(date),sofaLive()];const settled=await Promise.allSettled(tasks);for(let i=0;i<ESPN_LEAGUES.length;i++){const r=settled[i];if(r.status==='fulfilled')c.push(...r.value);else errors.push(`ESPN ${ESPN_LEAGUES[i]}: ${r.reason?.message||'erro'}`)}const ss=settled[ESPN_LEAGUES.length],sl=settled[ESPN_LEAGUES.length+1];if(ss?.status==='fulfilled')d=ss.value;else errors.push(`Sofascore agenda: ${ss?.reason?.message||'erro'}`);if(sl?.status==='fulfilled')e=sl.value;else errors.push(`Sofascore live: ${sl?.reason?.message||'erro'}`);sources.espn=c.length;sources.sofascoreSchedule=d.length;sources.sofascoreLive=e.length;
let games=mergeGames(mergeGames(mergeGames(mergeGames(a,b),c),d),e);games=games.sort((x,y)=>(Number(y.live)-Number(x.live))||((x.timestamp||0)-(y.timestamp||0)));return send(res,200,{date,count:games.length,liveCount:games.filter(g=>g.live).length,games,sources,reference:'Sofascore schedule + integrated football data providers',errors})};